font_family      JetBrainsMono Nerd Font
font_size        11.0
background_opacity 0.9

# Cursor
cursor_shape beam
cursor_trail 1

# Padding
window_margin_width 21.75

# No stupid close confirmation
confirm_os_window_close 0

# Use fish shell
shell fish

# Copy
map ctrl+c    copy_or_interrupt

# Search
map ctrl+f   launch --location=hsplit --allow-remote-control kitty +kitten search.py @active-kitty-window-id
map kitty_mod+f   launch --location=hsplit --allow-remote-control kitty +kitten search.py @active-kitty-window-id

# Scroll & Zoom
map page_up    scroll_page_up
map page_down    scroll_page_down

map ctrl+plus  change_font_size all +1
map ctrl+equal  change_font_size all +1
map ctrl+kp_add  change_font_size all +1
map ctrl+minus       change_font_size all -1
map ctrl+underscore       change_font_size all -1
map ctrl+kp_subtract       change_font_size all -1
map ctrl+0 change_font_size all 0
map ctrl+kp_0 change_font_size all 0

# Catppuccin Mocha
foreground              #CDD6F4
background              #1E1E2E
cursor                  #F5E0DC
color0                  #45475A
color1                  #F38BA8
color2                  #A6E3A1
color3                  #F9E2AF
color4                  #89B4FA
color5                  #F5C2E7
color6                  #94E2D5
color7                  #BAC2DE
color8                  #585B70
color9                  #F38BA8
color10                 #A6E3A1
color11                 #F9E2AF
color12                 #89B4FA
color13                 #F5C2E7
color14                 #94E2D5
color15                 #A6ADC8
