# GENERAL
general {
  no_fade_in = false
  grace = 1
  disable_loading_bar = false
  hide_cursor = false
  ignore_empty_input = true
  text_trim = true
}

# BACKGROUND
background {
    monitor =
    path = ~/dotfiles/.cache/current_wallpaper
    blur_passes = 0
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# LOCK ICON
label {
    monitor =
    text = 
    color = rgba(a8b8d0cc)
    font_size = 30
    font_family = JetBrains Mono Nerd Font Mono
    position = 0, -100
    halign = center
    valign = top
}

# TIME HR
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H")"
    color = rgba(d8e0edff)
    shadow_pass = 2
    shadow_size = 3
    shadow_color = rgb(0d1117)
    font_size = 180
    font_family = AlfaSlabOne
    position = 0, -250
    halign = center
    valign = top
}

# TIME MIN
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%M")"
    color = rgba(d8e0edff)
    shadow_pass = 2
    shadow_size = 3
    shadow_color = rgb(0d1117)
    font_size = 180
    font_family = AlfaSlabOne
    position = 0, -450
    halign = center
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%d %b %A")"
    color = rgba(a8b8d0aa)
    font_size = 14
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 0, -675
    halign = center
    valign = top
}

# INPUT FIELD BACKGROUND
shape {
    monitor =
    size = 400, 70
    color = rgba(242d3dff)
    shadow_passes = 1
    shadow_size = 6
    shadow_color = rgb(0d1117)
    rounding = 999
    border_size = 0
    position = 0, -200
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 70
    outline_thickness = 0
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0)
    dots_size = 0.25
    dots_spacing = 0.5
    dots_center = true
    font_color = rgba(d8e0edff)
    fade_on_empty = false
    font_family = JetBrains Mono Nerd Font Mono
    placeholder_text = <span foreground = "##a8b8d0bb"> $USER</span>
    hide_input = false
    rounding = 999
    position = 0, -200
    halign = center
    valign = center
    zindex = 10
}

# PLAYER IMAGE
image {
    monitor =
    path = ~/dotfiles/assets/music.webp
    size = 80
    rounding = 999
    shadow_passes = 1
    shadow_size = 2
    shadow_color = rgba(1e2430ff)
    border_size = 0
    rotate = 0
    reload_time = 1
    reload_cmd = bash ~/dotfiles/hypr/scripts/hyprlock.sh -music --arturl
    position = -245, 35
    halign = center
    valign = bottom
    zindex = 1
}

# PLAYER BOX
shape {
    monitor =
    color = rgba(242d3dff)
    shadow_passes = 1
    shadow_size = 10
    shadow_color = rgb(0d1117)
    size = 600, 100
    rounding = 999
    position = 0, 25
    halign = center
    valign = bottom
    zindex = 0
}

# PLAYER TITLE
label {
    monitor =
    text = cmd[update:1000] bash ~/dotfiles/hypr/scripts/hyprlock.sh -music --title
    color = rgba(d8e0edff)
    font_size = 13
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 20, 75
    halign = center
    valign = bottom
    zindex = 1
}

# PLAYER ARTIST
label {
    monitor =
    text = cmd[update:1000] bash ~/dotfiles/hypr/scripts/hyprlock.sh -music --artist
    color = rgba(a8b8d0bb)
    font_size = 11
    font_family = JetBrains Mono Nerd Font Mono
    position = 20, 45
    halign = center
    valign = bottom
    zindex = 1
}

# PLAYER PLAY/PAUSE
label {
    monitor =
    text = cmd[update:1000] bash ~/dotfiles/hypr/scripts/hyprlock.sh -music --status
    color = rgba(88c0d0ff)
    font_size = 35
    font_family = JetBrains Mono Nerd Font Mono
    onclick = playerctl play-pause
    position = 255, 45
    halign = center
    valign = bottom
    zindex = 2
}