max-gamma = 1.0

profile {
    time = 6:00
    identity = true        # Tagesfarben
}

profile {
    time = 20:00
    temperature = 3500     # warm aber noch angenehm
    gamma = 0.8
}

profile {
    time = 22:30
    temperature = 2700     # sehr warm kurz vor Schlaf
    gamma = 0.8
}