source = ~/dotfiles/hypr/hyprland/autostart.conf
source = ~/dotfiles/hypr/hyprland/monitor.conf
source = ~/dotfiles/hypr/hyprland/workspace.conf
source = ~/dotfiles/hypr/hyprland/input.conf
source = ~/dotfiles/hypr/hyprland/design.conf
source = ~/dotfiles/hypr/hyprland/bindings.conf
source = ~/dotfiles/hypr/hyprland/windowrules.conf