# ── Autostart ─────────────────────────────────────────────
exec-once = hyprpaper
exec-once = hyprsunset
exec-once = sleep 1 && ~/dotfiles/hypr/scripts/wallpaper.sh
exec-once = hypridle
exec-once = swayosd-server
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# exec-once = ~/.dotfiles/ags/shell.sh

# Audio
exec-once = easyeffects --hide-window --service-mode

# Clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Cursor
exec-once = hyprctl setcursor Nordic-cursors 24